# Generated by Django 3.1 on 2021-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('file', models.TextField()),
            ],
        ),
    ]
